export const TAMPIL_MENU = 'TAMPIL_MENU'
export const PILIH_MENU  = 'PILIH_MENU'
export const PESAN_MENU  = 'PESAN_MENU'
export const SHOW_MODAL  = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'